created desktop version styles for my portfolio
Ibranista/ibrahim-portfolio pull request #5
Opened 2022-11-02 16:28 UTC by Ibranista

I have added 3 separate stylesheets to make my page responsive.

2022-11-02 17:06 UTC, christianbiring1 requested changes
Hi @Ibranista , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
# STATUS: REQUEST CHANGES :recycle: 
![almost](https://user-images.githubusercontent.com/97100091/199553886-0f75078d-d1ed-4b22-85c3-ce5c69cd18e7.gif)


## Highlights
- [x] All linters checks are green :heavy_check_mark: 
- [ ] Descriptive PR `title` and `description`
- [x] Good commit message :+1: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Naming your HTML file `index.html` as is the case by convention, instead of `home`
- Also providing some straightforward walkthrough on how to run the project locally in your README by providing some commands.
ex. `git clone <REPO LINK>`
`cd <REPO DIRECTORY>`
`...`

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-03 16:32 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @Ibranista, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

-  No linter errors. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://user-images.githubusercontent.com/93039359/190567385-8e7bb3c0-7d3b-4d25-8385-61d173233786.gif)


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-03 16:32 UTC, Qoosim commented on styles/home-desktop.css
> +/* navbar section */
- [ ] You still need little work to make your mobile version look exactly like the figma design you chose. This is how it is still appeared on th mobile. 
![your-mobile-headline](https://user-images.githubusercontent.com/26597432/199777841-a7b95c89-649c-4293-a077-f92252d50746.png)

2022-11-03 16:32 UTC, Qoosim commented on styles/home-desktop.css
> +
- [ ] At screen size 768px, below is how your page appears which is different from how it appears on the figma design you chose.

### Your Design

![your-work-title-sect](https://user-images.githubusercontent.com/26597432/199778424-b90daec2-7a3b-4d99-9625-f0dd70fe6757.png)


### Figma Design

![temp-workstitle-sect](https://user-images.githubusercontent.com/26597432/199778490-ce88bd1c-0fb3-4565-aa2d-79eeffc884c2.png)

2022-11-04 00:33 UTC, fherrerao approved these changes
# ✅  🎆  STATUS APPROVED! ✅ 🎆 
#
Hi @Ibranista, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Great Job Yes GIF by Hollywood Suite](https://user-images.githubusercontent.com/91301423/197768588-bd30fde7-65cc-4249-9dd9-cc1fc1889a94.gif)


## Highlights
✔️  No linter errors.
✔️  You used the correct GitHub-Flow.
✔️  Good README
✔️  Good Commit Messages

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-04 07:05 UTC, merged