Javascript
Ibranista/ibrahim-portfolio pull request #9
Opened 2022-11-14 13:53 UTC by Ibranista

Added javascript interactivity to toggle the nav bar on small screen devices.

2022-11-14 14:06 UTC, youmari requested changes
Hi @Ibranista , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ Great commit messages
✔️ PRO PR
✔️ No linter error 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-14 14:06 UTC, youmari commented on pages/home.html
> +          </div>
- [ ]  it would be better if you use the same font color as in the Figma design. in order to match the design 

- [ ] also try to change the divider's color as well as in the Figma design 

- yours 
 
<img width="420" alt="Screenshot 2022-11-14 at 15 00 14" src="https://user-images.githubusercontent.com/61790587/201679569-1b73fc95-5038-413d-b37b-0d45951f7443.png">
- Figma
<img width="440" alt="Screenshot 2022-11-14 at 15 02 05" src="https://user-images.githubusercontent.com/61790587/201679644-c983c8d2-719c-445d-8fec-79224fb9c855.png">
- Color 
<img width="140" alt="Screenshot 2022-11-14 at 15 02 00" src="https://user-images.githubusercontent.com/61790587/201679910-dc1d899e-221d-4f4b-90f9-b072794b1d86.png">

2022-11-14 14:06 UTC, youmari commented on pages/home.html
> +            <li class="menu menu-1" id="menu-1"></li>
- [ ] your close button icon doesn't look like the one in the Figma design so please make sure to fix that 
- Yours 
<img width="77" alt="Screenshot 2022-11-14 at 15 00 10" src="https://user-images.githubusercontent.com/61790587/201680185-bac33c59-a739-4d25-b535-3c50312645d9.png">
- Figma 
<img width="80" alt="Screenshot 2022-11-14 at 15 01 39" src="https://user-images.githubusercontent.com/61790587/201680231-9eab9742-4db4-4e9a-a63f-245287c881fc.png">

2022-11-14 15:00 UTC, youmari commented on pages/home.html
> +            <li class="menu menu-1" id="menu-1"></li>
- [ ] it would be better if the menu icon shouldn't appear on the desktop version as in the requirements 
- Yours 
<img width="1440" alt="Screenshot 2022-11-14 at 15 59 45" src="https://user-images.githubusercontent.com/61790587/201692857-0c112648-3c0f-420f-8ca9-8cc61772c0c3.png">

2022-11-15 04:42 UTC, mgmediaweb requested changes
Hi @Ibranista , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost1](https://user-images.githubusercontent.com/41912912/201827270-e699b6d7-ba0c-41b0-a5c5-270269157b7c.gif)

 ## Highlights 💯 
- Good job following the advice of the previous reviewer ✔️ 

 ## Required Changes ♻️


_Check the comments under the review._

## Optional suggestions

[OPTIONAL] Kindly, I suggest that by convention the input file of your page is called index.html and is in the root of your project

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-15 04:42 UTC, mgmediaweb commented on pages/home.html
> +          </div>
Good job following the advice of the previous reviewer

2022-11-15 04:42 UTC, mgmediaweb commented on pages/home.html
> +            <li class="menu menu-1" id="menu-1"></li>
![image](https://user-images.githubusercontent.com/41912912/201827639-addcbbdf-6fe1-4a97-ac54-4e190023c865.png)

Good job styling the "X", but you need to use the corresponding color from Figma

2022-11-15 04:42 UTC, mgmediaweb commented on pages/home.html
> +            <li class="menu menu-1" id="menu-1"></li>
![image](https://user-images.githubusercontent.com/41912912/201827916-c6587f95-e68e-4c86-9f79-827ce96ae2eb.png)

Kindly, I suggest you consider the advice of the previous reviewer, the hamburger menu is still visible on the desktop version and should disappear

2022-11-15 05:06 UTC, topeogunleye reviewed
Hi @Ibranista and Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ⚠️

   - You have submitted a project that has failing linters, Kindly make sure your linters are all passing before submitting the PR.

## Stlylint AutoFix
- [ ] if you have a lot of CSS line errors, I kindly suggest you fix them with `npx stylelint --fix "**/*.{css,scss}"`, but please get used to fixing the errors line by line also because it'll help you learn best practices.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

>Invalid Code Review Request **does not count** into the code reviews limit.

2022-11-15 05:30 UTC, HAMMAS-SALEEM approved these changes
# Status: Approved :green_circle: :1st_place_medal: :100:
![success](https://camo.githubusercontent.com/6ada59f6189497c1c2cae6d06f8154b7307a58643f232340e288140ed469eb28/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966)

## Hey @Ibranista :wave:

Great work on implementing the requested changes. Your project is complete. :blush:
There is nothing else to say about your project. :+1:


## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following Github Flow
✔️ Following requirements

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-15 05:30 UTC, HAMMAS-SALEEM commented on pages/home.html
> +            <li><a href="#About" class="nav-link">About</a></li>
![Capture](https://user-images.githubusercontent.com/93039359/201834003-da0e9ccf-e50c-41b1-aa3e-9783cdbc28c9.PNG)

**[Optional]**

- [ ] When i click on any of the **Portfolio** navlink shown in the image above ⬆️ in the desktop version then they work as expected but after clicking these link get vanish. Kindly fix this issue 👍

2022-11-18 06:34 UTC, merged